name: build

on:
  release:
    types: [created]
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ startsWith(github.ref, 'refs/tags/v') && 'release' || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/v') }}

env:
  # renovate: datasource=npm depName=npm
  NPM_VERSION: "11"
  # renovate: datasource=npm depName=@microbit-foundation/python-editor-v3-microbit registryUrl=https://npm.pkg.github.com
  THEME_VERSION: 0.3.0
  # renovate: datasource=npm depName=@microbit-foundation/website-deploy-aws registryUrl=https://npm.pkg.github.com
  DEPLOY_AWS_VERSION: "0.6.0"
  # renovate: datasource=npm depName=@microbit-foundation/website-deploy-aws-config registryUrl=https://npm.pkg.github.com
  DEPLOY_AWS_CONFIG_VERSION: "0.10.1"

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    env:
      AWS_DEFAULT_REGION: eu-west-1
      PRODUCTION_CLOUDFRONT_DISTRIBUTION_ID: E2ELTBTA2OFPY2
      STAGING_CLOUDFRONT_DISTRIBUTION_ID: E2ELTBTA2OFPY2
      REVIEW_CLOUDFRONT_DISTRIBUTION_ID: E3267W09ZJHQG9
      VITE_FOUNDATION_BUILD: ${{ github.repository_owner == 'microbit-foundation' }}
      # This feature is also controlled by a client-side feature flag that is disabled by default for the moment
      FEATURE_PWA: ${{ github.repository_owner == 'microbit-foundation' }}

    steps:
      # Note: This workflow disables deployment steps and micro:bit branding installation on forks.
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Configure node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24.x
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      - run: npm install -g npm@${{ env.NPM_VERSION }} --registry=https://registry.npmjs.org
      - uses: microbit-foundation/npm-package-versioner-action@v3
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install --no-save @microbit-foundation/python-editor-v3-microbit@${{ env.THEME_VERSION }} @microbit-foundation/website-deploy-aws@${{ env.DEPLOY_AWS_VERSION }} @microbit-foundation/website-deploy-aws-config@${{ env.DEPLOY_AWS_CONFIG_VERSION }}
        if: github.repository_owner == 'microbit-foundation'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: node ./bin/print-ci-env-stage.cjs >> $GITHUB_ENV
      - run: node ./bin/print-ci-env-public-url.cjs >> $GITHUB_ENV
      - run: npm run ci
        env:
          VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - run: mkdir -p /tmp/app${BASE_URL} && cp -r build/* /tmp/app${BASE_URL} && npx serve --no-clipboard -l 3000 /tmp/app &
        if: env.STAGE == 'REVIEW' || env.STAGE == 'STAGING'
      - run: curl --insecure -4 --retry 7 --retry-connrefused http://localhost:3000 1>/dev/null
        if: env.STAGE == 'REVIEW' || env.STAGE == 'STAGING'
      - name: Run Playwright tests
        if: env.STAGE == 'REVIEW' || env.STAGE == 'STAGING'
        uses: docker://mcr.microsoft.com/playwright:v1.62.1-noble
        with:
          args: npx playwright test
      - name: Store reports
        if: (env.STAGE == 'REVIEW' || env.STAGE == 'STAGING') && failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: reports
          path: reports/
          retention-days: 3
      - run: npm run deploy
        if: github.repository_owner == 'microbit-foundation' && (env.STAGE == 'REVIEW' || success())
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WEB_DEPLOY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WEB_DEPLOY_AWS_SECRET_ACCESS_KEY }}
      - run: npm run invalidate
        if: github.repository_owner == 'microbit-foundation' && (env.STAGE == 'REVIEW' || success())
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WEB_DEPLOY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WEB_DEPLOY_AWS_SECRET_ACCESS_KEY }}
